import { useRouter } from "next/router";
import useSWR from "swr";
import type { NextPage } from "next";
import Head from "next/head";
import { PokemonModel } from "types/PokemonModel";
import { PokemonList, Pagination } from "components/generic";
import { serverSideTranslations } from 'next-i18next/serverSideTranslations'

const getOffset = (x: string): number | null => {
  const url = new URL(x);
  const params = new URLSearchParams(url.search);
  const offset = params.get("offset");

  return offset ? Number(offset) : null
};

const Home: NextPage = () => {
  const { query } = useRouter();

  const offset = query.offset ? Number(query.offset) : null;
  const { data } = useSWR<PokemonModel>(`/pokemon?offset=${offset}`);

  const next = data?.next ? getOffset(data.next) : null;
  const previous = data?.previous ? getOffset(data.previous) : null;

  return !data ? (
    <>LOADING...</>
  ) : (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="favicon.ico" />
      </Head>

      <main>
        <PokemonList pokemonList={data.results}></PokemonList>
        <Pagination 
        count={data.count} 
        previous={previous}
        next={next} 
        />
      </main>
    </>
  );
};

export default Home 

export async function getStaticProps({ locale }: { locale: string }) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ["common", "pagination"])),
      // Will be passed to the page component as props
    },
  }
}
